system wide scheme
Description: system wide scheme
 Implement system wide scheme:
 - sympow can be now called system wide as any regular executable;
 - precomputed plain data mesh files are kept in PKGDATADIR/datafiles
  (typically PKGDATADIR is /usr/share/sympow);
 - generated plain data mesh files are recorded in CACHEDIR/datafiles
  (by default CACHEDIR is HOME/.sympow);
 - binary data mesh files are created on the fly and stored in cache
   directories, the ones from the precomputed plain data mesh files are
	 stored in PKGCACHEDIR/datafiles/ENDIANTUPLE (typilcally PKGCACHEDIR
	 is /var/cache/sympow, and ENDIANTUPLE is a tuple characterizing the
	 architecture endianness or so for double floats) and the ones from the
	 generated plain data meshes are put in CACHEDIR/datafiles/ENDIANTUPLE;
 - the register data file param_data is in CACHEDIR/datafiles;
 - the data in CACHEDIR/datafiles are authoritative;
 - the employed script is in PKGLIBDIR (typically /usr/lib/sympow);
 - CACHEDIR, PKGCACHEDIR, PKGLIBDIR, and PKGDATADIR can be set via
   environment variables with their respective name prepended with
	 SYMPOW_ (it is recommended to set absolute paths whenever possible);
 - the basename of CACHEDIR must begin with `sympow' (typically `sympow');
 - CACHEDIR is created on the fly with respect to permissions and privileges
   whenever the following conditions are satisfied: (i) it terminates with at
	 least three directory separators (the creation is group-centric when the
	 number of separators is greater or equal to six, user-centric otherwise),
	 (ii) its parent directory exists (its basename either begins with `sympow'
	 or is implicitly assumed to be `sympow');
 - ENDIANTUPLE is set by default to bin.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2016-12-26

diff --git a/Configure b/Configure
--- a/Configure
+++ b/Configure
@@ -5,6 +5,9 @@ then
 echo "**ERROR**: Configure does not take any options for SYMPOW"; exit;
 fi
 
+PREFIX="/usr/local"
+VARPREFIX="/var/local"
+
 FILE="Makefile.new"
 CONFIG="config.h"
 RM=`which \rm`
@@ -15,6 +18,8 @@ fi
 $RM -f $FILE
 $RM -f $CONFIG
 VERSION=1.023
+echo "#define PREFIX \"$PREFIX\"" >> $CONFIG
+echo "#define VARPREFIX \"$VARPREFIX\"" >> $CONFIG
 echo "#define VERSION \"$VERSION\"" >> $CONFIG
 echo "VERSION = $VERSION" >> $FILE
 echo "#define RM \"$RM\"" >> $CONFIG
@@ -111,10 +116,10 @@ try_add_CFLAG()
     return 2
 }
 
-# Let move to 21st century
-try_add_CFLAG '-std=c11' bypass
+# Let move to 21st century and add GNU features (asprintf)
+try_add_CFLAG '-std=gnu11' bypass
 if [ $? -ne 0 ]; then
-    echo >&2 "Error: move to 21st century is denied"
+    echo >&2 "Error: moving to 21st century and adding GNU feature are denied"
     exit 1
 fi
 
@@ -268,6 +273,13 @@ echo "	\$(CC) \$(CPPFLAGS) \$(CFLAGS) \$(OPT) \$(DEFS) -c -o \$@ \$<" >> $FILE
 echo "clean:" >> $FILE
 ##echo "	\$(RM) -f \$(OBJSf) sympow \$(TILDES) \$(TARS)" >> $FILE
 echo "	\$(RM) -f \$(OBJS) sympow \$(TILDES)" >> $FILE
+echo "install: all" >> $FILE
+echo "	install -d \$(DESTDIR)/$PREFIX/bin" >> $FILE
+echo "	install -d \$(DESTDIR)/$PREFIX/lib/sympow" >> $FILE
+echo "	install -d \$(DESTDIR)/$PREFIX/share/sympow" >> $FILE
+echo "	install -t \$(DESTDIR)/$PREFIX/bin sympow" >> $FILE
+echo "	install -t \$(DESTDIR)/$PREFIX/lib/sympow new_data" >> $FILE
+echo "	cp -t \$(DESTDIR)/$PREFIX/share/sympow standard1.gp standard2.gp standard3.gp" >> $FILE
 ####if [ -n "$TAR" ];
 ####then
 ####echo "source:" >> $FILE
